// +build ignore

// This program generates datafiles.go
package main

import (
	"io/ioutil"
	"log"
	"os"
	"text/template"
	"time"
)

func DataFile(n string) []byte {
	d, err := ioutil.ReadFile(n)
	die(err)
	return d
}

func main() {
	f, err := os.Create("misc/datafiles.go")
	die(err)
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		DejavusansTTF []byte
	}{
		Timestamp: time.Now(),
		DejavusansTTF: DataFile("data/DejaVuSans.ttf"),
	})
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// These are data files built in to wingo.
// {{ .Timestamp }}
// 

package misc

var (
	DejavusansTTF = []byte( {{with $x := .DejavusansTTF}}{{printf "%q" $x}}{{end}})
)
`))
